package sop_corba.ControladorCompraIntPackage;


/**
* sop_corba/ControladorCompraIntPackage/CompraDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Sunday, August 7, 2022 2:03:00 PM COT
*/

public final class CompraDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String tipo = null;
  public int valor = (int)0;
  public String lugar = null;
  public String fecha = null;
  public String medioPago = null;
  public String nit = null;

  public CompraDTO ()
  {
  } // ctor

  public CompraDTO (int _id, String _tipo, int _valor, String _lugar, String _fecha, String _medioPago, String _nit)
  {
    id = _id;
    tipo = _tipo;
    valor = _valor;
    lugar = _lugar;
    fecha = _fecha;
    medioPago = _medioPago;
    nit = _nit;
  } // ctor

} // class CompraDTO
