package sop_corba;


/**
* sop_corba/ControladorCompraIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Sunday, August 7, 2022 2:03:00 PM COT
*/

public interface ControladorCompraIntOperations 
{
  boolean imprimirCompra (sop_corba.ControladorCompraIntPackage.CompraDTO objCompra);
} // interface ControladorCompraIntOperations
