package sop_corba;


/**
* sop_corba/ControladorCompraInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Sunday, August 7, 2022 2:03:00 PM COT
*/

public interface ControladorCompraInt extends ControladorCompraIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControladorCompraInt
